@section('head')
    {!! "<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>" !!}
    {!! $page->appendAsset(url('/css/millionaire/funnel-style.css')) !!}
    {!! $page->appendAsset(url('/css/millionaire/members-style.css')) !!}
    {!! $page->appendAsset(url('/css/millionaire/style.css')) !!}
@append

@section('bottom-scripts')
    @com('funnel_scripts')
    {!! $page->appendAsset(url('/js/millionaire/jquery-ui.min.js')) !!}
    {!! $page->appendAsset(url('/js/millionaire/jquery.main7ef2.js')) !!}
    {!! $page->appendAsset(url('/js/millionaire/jquery.fitvids.js')) !!}
    {!! $page->appendAsset(url('/js/millionaire/membersOnLoad.js')) !!}
    {!! $page->appendAsset(url('/js/millionaire/script.js')) !!}
@append

@section('page-layout')
    <div id="wrapper">
        <header id="header">
            <div class="logo"><a href="#"><img src="/img/millionaire/logo-min.png" alt="The Online Millionaire System"></a></div>
        </header>
        <main role="main" id="main">
            <div class="promo-block">
                <section class="promo-section add">
                    <div class="holder">
                        <h1>automate your profits</h1>
                        <div class="step-block">
                            <div class="step-row second-step">
                                <div class="step-line">
                                    <div class="step one">
                                        <span class="num">1</span>
                                        <span class="top">step</span>
                                        <span class="bottom">Signup</span>
                                    </div>
                                    <div class="step two active">
                                        <span class="num">2</span>
                                        <span class="top">step</span>
                                        <span class="bottom">Create your account</span>
                                    </div>
                                    <div class="step three">
                                        <span class="num">3</span>
                                        <span class="top">step</span>
                                        <span class="bottom">You're done! Make profits</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-box">
                                <h2><b>Congratulations,</b> sign up now and get your lifetime free subscription!</h2>
                                <div class="wl-signup">
                                    @include('funnels.layouts._partials._form-mobile', ['funnelId' => $page->getParent()->id]);
                                </div>
                                <span class="message">limited time offer!</span>
                                <ul class="logo-list">
                                    <li><img src="/img/millionaire/logo-01-min.png" alt="image description" width="32" height="32"></li>
                                    <li><img src="/img/millionaire/logo-02-min.png" alt="image description" width="97" height="31"></li>
                                    <li><img src="/img/millionaire/logo-03-min.png" alt="image description" width="28" height="30"></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>
                <div class="panel info">
                    <div class="holder">
                        <h2>PROFIT GENERATED BY MEMBERS:</h2>
                        <span class="count"><b class='counter'></b></span>
                        <p>Live updating trades that are made by TheOnlineMillionaireSystem members! All verified and confirmed by a third party.<br/>All accounts have been looked at by a a legal team before publishing on this website.</p>
                    </div>
                </div>
                <section class="main-section">
                    <div class="holder">
                        <div class="heading">
                            <h1>Our Success Stories</h1>
                            <p>All proof is verified by a third party. All accounts have been looked at by a CPA and legal team before <br>publishing on this website.</p>
                        </div>
                        <ul class="photo-block same-parent">
                            <li>
                                <img src="/img/millionaire/photo-04-min.jpg" alt="image description">
                                <div class="description same">
                                    <p>“I needed some extra income I could do from home. When I saw TheOnlineMillionaireSystem I knew instantly it was perfect for me. Extra cash was super useful in my life.”</p>
                                    <span class="author">Luke W. London, UK</span>
                                </div>
                            </li>
                            <li>
                                <img src="/img/millionaire/photo-02-min.jpg" alt="image description">
                                <div class="description same">
                                    <p>“This is Truly amazing! I would like to say Thank you for TheOnlineMillionaireSystem!! I have made $47,580 in just 8 weeks.”</p>
                                    <span class="author">Sarah G.  Johannesburg, South Africa</span>
                                </div>
                            </li>
                            <li>
                                <img src="/img/millionaire/photo-03-min.jpg" alt="image description">
                                <div class="description same">
                                    <p>“I found out about TheOnlineMillionaireSystem from a co-worker that was making thousands of Euros a week using the system. At the beginning I was skeptical, but now that I reached my goal of 3,500 euros a week. I can confidently say that it works.”</p>
                                    <span class="author">Conor S. Dublin, Ireland</span>
                                </div>
                            </li>
                            <li>
                                <img src="/img/millionaire/photo-05-min.jpg" alt="image description">
                                <div class="description same">
                                    <p>“When I retired, I realized I did not save enough for the retirement I deserved… now that I found TheOnlineMillionaireSystem My life have changed and I am planning a long trip to Europe.”</p>
                                    <span class="author">Keira D. Wellington New Zeeland</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </section>
                <div class="panel">
                    <div class="holder">
                        <h2>Get started today before all spots are filled!</h2>
                        <a href="#header" class="btn-scroll">GET FREE ACCESS NOW!</a>
                        <p>Start on your path to financial freedom today! You are guaranteed to make money. Sign up now for FREE. Let's get YOU started!</p>
                    </div>
                </div>
                <section class="table-section">
                    <div class="holder">
                        <h1>LIVE TRADES BEEN MADE BY THE SYSTEM NOW!</h1>
                        <h2>LIVE SYSTEM TRADES – APPROVED & VERIFIED</h2>
                        <div class="table-box">
                            <div id="info-table" class="info-table">
                                <div class="tr">
                                    <div class="th">TheOnlineMillionaireSystem Members</div>
                                    <div class="th">Profit</div>
                                    <div class="th">Trade Time</div>
                                    <div class="th">Currency</div>
                                </div>
                            </div>
                            <div id="live_trades" class="info-table">
                            </div>
                        </div>
                    </div>
                </section>
                <div class="link-row">
                    <div class="holder">
                        <div class="link-list">
                            {{--<a class="email" href="mailto:&#115;&#117;&#112;&#112;&#111;&#114;&#116;&#064;&#116;&#104;&#101;&#111;&#110;&#108;&#105;&#110;&#101;&#109;&#105;&#108;&#108;&#105;&#111;&#110;&#097;&#105;&#114;&#101;&#115;&#121;&#115;&#116;&#101;&#109;&#046;&#099;&#111;&#109;">--}}
                                {{--<span class="title">Email</span>--}}
                                {{--<span>support@theonlinemillionairesystem.co</span>--}}
                            {{--</a>--}}
                            {{--<a class="chat" href="#">--}}
                                {{--<span class="title">24/7 Live Chat</span>--}}
                                {{--<span>Available For Members</span>--}}
                            {{--</a>--}}
                            <a class="terms" id="open-terms" onclick="openTerms()">
                                <span class="title">Terms</span>
                                <span>Disclaimer &amp; Privacy Policy</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer id="footer">
            <div class="holder">
                <span class="copy">Copyright 2015 | All Right Reserved by OnlineMillionaireSystem</span>
            </div>
        </footer>
    </div>
    <div class="popup-holder">
        <div id="popup1" class="lightbox popup">
            <div class="lightbox-holder">
                <h2>WELCOME TO <mark>the Online Millionaire System</mark></h2>
                <div class="step-row">
                    <div class="step-line">
                        <div class="step one">
                            <span class="num">1</span>
                            <span class="top">step</span>
                            <span class="bottom"><b>FUND</b> Your Broker Account.</span>
                        </div>
                        <div class="step two">
                            <span class="num">2</span>
                            <span class="top">step</span>
                            <span class="bottom">Push AUTO TRADE to <b>ACTIVATE</b></span>
                        </div>
                        <div class="step three active">
                            <span class="num">3</span>
                            <span class="top">step</span>
                            <span class="bottom">Watch your <b>PROFIT</b> grow</span>
                        </div>
                    </div>
                </div>
                <div class="video-holder">
                    <!--<iframe width="560" height="315" src="https://www.youtube.com/embed/a17Zqq_EQTI?rel=0&amp;controls=0&amp;showinfo=0&amp;" allowfullscreen></iframe>-->
                </div>
                <a href="#" class="btn">get free access now!</a>
                <p>Once you click on <a href="#">Get Started</a> button, <mark><b>the Online Millionaire System</b></mark> deposit page account will <br>open, so you can easily make your deposit and activate your account.  <br>Gladly, <mark class="large"><b>THE Online Millionaire System</b></mark></p>
            </div>
        </div>
    </div>
@endsection